# Generated by Django 5.2.9 on 2026-05-12 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_item_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='is_available',
        ),
        migrations.AddField(
            model_name='item',
            name='availability',
            field=models.CharField(choices=[('available', 'Available'), ('unavailable', 'Unavailable'), ('special', 'Special')], default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='tracking_code',
            field=models.CharField(db_index=True, max_length=40, unique=True),
        ),
       
    ]
